# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_criptos = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_criptos.setGeometry(QtCore.QRect(40, 70, 201, 21))
        self.comboBox_criptos.setCurrentText("")
        self.comboBox_criptos.setObjectName("comboBox_criptos")
        self.comboBox_criptos.addItem("Bitcoin")
        self.comboBox_criptos.addItem("Ethereum")
        self.comboBox_criptos.addItem("Binance Coin")
        self.comboBox_criptos.addItem("Litecoin")
        self.comboBox_criptos.addItem("Bitcoin Cash")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 70, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 120, 151, 188))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btc_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btc_button.setObjectName("btc_button")
        self.verticalLayout.addWidget(self.btc_button)
        self.eth_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.eth_button.setObjectName("eth_button")
        self.verticalLayout.addWidget(self.eth_button)
        self.bnb_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bnb_button.setObjectName("bnb_button")
        self.verticalLayout.addWidget(self.bnb_button)
        self.ltc_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ltc_button.setObjectName("ltc_button")
        self.verticalLayout.addWidget(self.ltc_button)
        self.bch_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bch_button.setObjectName("bch_button")
        self.verticalLayout.addWidget(self.bch_button)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 140, 561, 341))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("BitcoinPrice.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(290, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setAutoFillBackground(False)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        save_btn = QtWidgets.QPushButton("Save", MainWindow)
        save_btn.move(500,500)

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Ver precio"))
        self.btc_button.setText(_translate("MainWindow", "Bitcoin"))
        self.eth_button.setText(_translate("MainWindow", "Ethereum"))
        self.bnb_button.setText(_translate("MainWindow", "Binance Coin"))
        self.ltc_button.setText(_translate("MainWindow", "Litecoin"))
        self.bch_button.setText(_translate("MainWindow", "Bitcoin Cash"))
        self.title.setText(_translate("MainWindow", "NeoCriptoNetwork"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
