# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget,plot
import pyqtgraph as pg
import sys
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_criptos = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_criptos.setCurrentText("")
        self.comboBox_criptos.setObjectName("comboBox_criptos")
        self.comboBox_criptos.addItem("Bitcoin")
        self.comboBox_criptos.addItem("Ethereum")
        self.comboBox_criptos.addItem("Binance Coin")
        self.comboBox_criptos.addItem("Litecoin")
        self.comboBox_criptos.addItem("Bitcoin Cash")
        self.horizontalLayout.addWidget(self.comboBox_criptos)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btc_button = QtWidgets.QPushButton(self.centralwidget)
        self.btc_button.setObjectName("btc_button")
        self.verticalLayout.addWidget(self.btc_button)
        self.eth_button = QtWidgets.QPushButton(self.centralwidget)
        self.eth_button.setObjectName("eth_button")
        self.verticalLayout.addWidget(self.eth_button)
        self.bnb_button = QtWidgets.QPushButton(self.centralwidget)
        self.bnb_button.setObjectName("bnb_button")
        self.verticalLayout.addWidget(self.bnb_button)
        self.ltc_button = QtWidgets.QPushButton(self.centralwidget)
        self.ltc_button.setObjectName("ltc_button")
        self.verticalLayout.addWidget(self.ltc_button)
        self.bch_button = QtWidgets.QPushButton(self.centralwidget)
        self.bch_button.setObjectName("bch_button")
        self.verticalLayout.addWidget(self.bch_button)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setAutoFillBackground(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(728, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.widget = PlotWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(97, 97, 97);")
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.plot([1,2,3,4,5,6,7,8,9,10],[30,32,34,35,36,37,38,32,39,30])

    def plot(self, hour, temperature):
        self.widget.plot(hour, temperature)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Ver precio"))
        self.btc_button.setText(_translate("MainWindow", "Bitcoin"))
        self.eth_button.setText(_translate("MainWindow", "Ethereum"))
        self.bnb_button.setText(_translate("MainWindow", "Binance Coin"))
        self.ltc_button.setText(_translate("MainWindow", "Litecoin"))
        self.bch_button.setText(_translate("MainWindow", "Bitcoin Cash"))
        self.title.setText(_translate("MainWindow", "NeoCriptoNetwork"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
